### ISSUE TITLE
Add setup files to make viya4-ark pip installable via Git

### ISSUE THREAD

**Issue by sasjowood** [sassoftware/viya4-ark#110]
Add the requisite files to make the viya4-ark project pip installable via the git protocol:

https://setuptools.readthedocs.io/en/latest/userguide/quickstart.html

This allows users to use the model classes supporting the CLI for their own purposes.

**Comment by kevinlinglesas** [comment]
Addressed in [release 1.4.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.4.0)
