### ISSUE TITLE
Request to add storage information for internal/external database to the deployment report

### ISSUE THREAD

**Issue by cuddlehub** [sassoftware/viya4-ark#115]
This is to request to add storage information for database to the deployment report. 
There are two types: internal/external. 
With external database, host/port/user/dbname informations will be listed in the report.

**Comment by cuddlehub** [comment]
Code merged.

**Comment by kevinlinglesas** [comment]
Addressed in [release 1.4.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.4.0)

**Comment by cuddlehub** [comment]
Note: Code was pushed but this feature is not visible on the report in release 1.4.0.
