### ISSUE TITLE
Pre_install_check:  Migrate hello-ingress manifest to use the networking.k8s.io/v1 API version, available since v1.19.

### ISSUE THREAD

**Issue by lasiva** [sassoftware/viya4-ark#118]
The extensions/v1beta1 and networking.k8s.io/v1beta1 API versions of Ingress will no longer be served in v1.22.

Migrate manifests and API clients to use the networking.k8s.io/v1 API version, available since v1.19.

**Comment by erharb** [comment]
Keep in mind we will be supporting both version for some amount of time.

**Comment by lasiva** [comment]
Ok.  I will be testing with v1.19 and later

**Comment by kevinlinglesas** [comment]
Addressed in [release 1.4.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.4.0)
