### ISSUE TITLE
Check disk size in pre-installation check

### ISSUE THREAD

**Issue by Andy-Tr** [sassoftware/viya4-ark#121]
The pre-installation check should check the disk size of the machines to make sure it meets the minimum documented in the Virtual machine requirements.

**Comment by lasiva** [comment]
Thank you.  We will address it with issue  #79

**Comment by kevinlinglesas** [comment]
Issue #79  addressed by release [1.5.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.5.0)
