### ISSUE TITLE
Suggestion: Include version number for ingress type

### ISSUE THREAD

**Issue by saschu6106** [sassoftware/viya4-ark#123]
The Deployment Report currently notes the Ingress Type.  Would it be possible to also include the version of the Ingress type?

**Comment by kevinlinglesas** [comment]
sounds like a good suggested enhancement.

**Comment by AlissaSchleich** [comment]
A feature request has been entered for updating the deployment report to include a version number.

**Comment by cuddlehub** [comment]
Re-open the request since the work was not done yet.

**Comment by cuddlehub** [comment]
Code was pushed in July. Issue closed.
