### ISSUE TITLE
Pre_install_check: Syntax error in example commands for Known Issues 

### ISSUE THREAD

**Issue by lasiva** [sassoftware/viya4-ark#124]
The 2nd command should be "pod", not "pos"
 Suggested commands to delete resources before running the tool again:
        kubectl -n <namespace> delete replicaset.apps/hello-world-6665cf748b
        kubectl -n <namespace> delete pos/hello-world-6665cf748b-5x2jq
        kubectl -n <namespace> delete pod/hello-world-6665cf748b-tkq79

**Comment by kevinlinglesas** [comment]
Addressed in [release 1.4.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.4.0)
