### ISSUE TITLE
Pre_install_check: Correct Error in the instructions to collect the INGRESS HOST

### ISSUE THREAD

**Issue by lasiva** [sassoftware/viya4-ark#126]
$ export INGRESS_HOST=**externalIP**=$(kubectl -n <ingress-namespace> get service <nginx-ingress-controller-name> -o jsonpath='{.status.loadBalancer.ingress[*].ip}')
 
But if you use the INGRESS_HOST variable after that the check will fail because of the "externalIP=" string. Remove externalIP

**Comment by kevinlinglesas** [comment]
Addressed in [release 1.4.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.4.0)
