### ISSUE TITLE
Deployment Report: Recursion error when generating report

### ISSUE THREAD

**Issue by sasjowood** [sassoftware/viya4-ark#130]
A recursion error is possible under certain conditions when running the deployment report.

**Comment by kevinlinglesas** [comment]
Addressed in [release 1.4.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.4.0)

**Comment by sasjowood** [comment]
There is a longer-term fix coming for this issue, reopening.

**Comment by sasjowood** [comment]
Long-term fix addressed in [release 1.5.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.5.0)
