### ISSUE TITLE
Pre_install_check: Does not report all available Storage classes on an Azure cluster

### ISSUE THREAD

**Issue by lasiva** [sassoftware/viya4-ark#135]
On an Azure report only 2 classes were reported as follows:
![image](https://user-images.githubusercontent.com/45047672/129278439-08c6da6f-1c77-4013-8b41-54e081fbcbc4.png)

The tool should have detailed all the storage classes like below:
![image](https://user-images.githubusercontent.com/45047672/129278363-58c96612-1ffd-4944-b0c5-28c1583d9925.png)

**Comment by kevinlinglesas** [comment]
Addressed by [release 1.5.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.5.0)
