### ISSUE TITLE
Update example commands for consistency

### ISSUE THREAD

**Issue by Andy-Tr** [sassoftware/viya4-ark#137]
The example commands should be consistent.  Some show a $ in front of the command.   For https://github.com/sassoftware/viya4-ark/tree/master/pre_install_report ,  has both:
$ python3 -m pip install -r requirements.txt
and
python3 viya-ark.py pre-install-report -h
.
Can all the commands not have the $, so it is easier to cut and paste them?

**Comment by kevinlinglesas** [comment]
Thanks, @Andy-Tr  for the comments/suggestions.   What you point out makes sense, so we will work on making the documentation consistent and easier to copy/paste command.

**Comment by kevinlinglesas** [comment]
Addressed by [release 1.5.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.5.0)
