### ISSUE TITLE
Provide full commands for http vs https example

### ISSUE THREAD

**Issue by Andy-Tr** [sassoftware/viya4-ark#138]
The full command syntax should be shown for using http vs https in https://github.com/sassoftware/viya4-ark/tree/master/pre_install_report 
Use the values gathered on the command line for http or https as appropriate for your deployment:

 -i nginx  -H $INGRESS_HOST -p $INGRESS_HTTP_PORT 
 -i nginx  -H $INGRESS_HOST -p $INGRESS_HTTPS_PORT

The full example command should be shown.  It would also be helpful to have the HTTP and HTTPS examples in different text boxes, so it is clear which one to use.

**Comment by kevinlinglesas** [comment]
Thanks, @Andy-Tr for the comments/suggestions.   We will work on improving the documentation based on your input.

**Comment by kevinlinglesas** [comment]
Addressed by [release 1.5.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.5.0)
