### ISSUE TITLE
Pre-install-check tool should expose sample application correctly in Openshift environment

### ISSUE THREAD

**Issue by lasiva** [sassoftware/viya4-ark#150]
1. The Pre-install-check tool will now support an --ingress value of _openshift-ingress_ for Red Hat OpenShift environment

2. The pre-install-check tool deploys a route with no host name, and then the OpenShift Container Platform automatically generates a host/port for the associated service which can then be used to direct traffic to the service.  The user must specify a value of _openshift-ingress_ for option --ingress on the command line, but host and port value is not required.
python viya-ark.py  pre_install_report --ingress **_openshift-ingress_** --namespace lasiva --debug

**Comment by kevinlinglesas** [comment]
Issue addressed in release [1.6.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.6.0)
