### ISSUE TITLE
Deployment Report should not display none existing resource types

### ISSUE THREAD

**Issue by cuddlehub** [sassoftware/viya4-ark#151]
Under Resource Information, we saw some none existing resource types which should not be in the report.

Kind    Type                                                   Count   SAS Custom Resource
None    httpproxies.projectcontour.io           0          False
None    routes.route.openshift.io                  0          False
None    virtualservices.networking.istio.io     0          False

**Comment by kevinlinglesas** [comment]
Issue addressed in release [1.6.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.6.0).
