### ISSUE TITLE
Typo in pre_install_check_permissions.py

### ISSUE THREAD

**Issue by DewyattStanfield** [sassoftware/viya4-ark#162]
While troubleshooting why I was getting insufficient for creating a custom resource with the RBAC service account, I noticed a typo in the file viya4-ark/pre_install_report/library/pre_install_check_permissions.py shows a typo for the command.  Line 587 has this defined self.logger.debug("get_**rbace**_group_cmd found = {}, sample_deployment = {}

Unfortunately, it didn't solve the problem, but that is for a different issue.

**Comment by lasiva** [comment]
Thanks for bringing this issue to our notice.  I will update here once the  typo is fixed and pushed to the master branch.

**Comment by kevinlinglesas** [comment]
This issue should have been closed out as the typo was fixed along with (#164).   Therefore, this issue was fixed in [Release 1.8.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.8.0).
