### ISSUE TITLE
Errant warning in Deployment Report when deprecated Ingress definitions aren't found

### ISSUE THREAD

**Issue by sasjowood** [sassoftware/viya4-ark#167]
A warning is displayed at the top of the deployment report when the deployment is using NGINX as an ingress controller, but the beta, deprecated version of Ingress objects are not present. This was a hold-over while transitioning from the deprecated to the new, current Ingress objects and can now be removed.

**Comment by lasiva** [comment]
This Issue is addressed in [Release 1.8.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.8.0)
