### ISSUE TITLE
Pre-install-check tool not compatible with Azure provisioners in K8s 1.21 +

### ISSUE THREAD

**Issue by lasiva** [sassoftware/viya4-ark#169]
Tool does not recognize new provisioners introduced by Azure/AKS. See https://github.com/Azure/AKS/releases.                                    Kubernetes 1.21+ Existing and newly created clusters use CSI Driver provisioners disk.csi.azure.com and file.csi.azure.com. There are no in-tree provisioners anymore (kubernetes.io/azure-disk and kubernetes.io/azure-file).  Tool continues to detect older kubernetes.io/azure-disk and kubernetes.io/azure-file currently.

**Comment by kevinlinglesas** [comment]
Closing this issue as we've not had any requirements for this enhancement.   This issue can be re-opened in the future if needed.
