### ISSUE TITLE
What are alternatives to example node-hello image?

### ISSUE THREAD

**Issue by xelat** [sassoftware/viya4-ark#197]
The customer is using [Aqua Security](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/aqua-security.aqua-security?tab=overview) to prevent container images that haven’t been subject to security scan from running on the cluster.

In pre_install_report/test/test_data/yaml_data/hello-application.yaml, we see the example image being used is gcr.io/google-samples/node-hello:1.0. This image is reported to contain vulnerabilities. Even we tried to pull and push that image to the customer's Container Registry but it still does not allow us to use it. What are the alternatives to this image?

**Comment by lasiva** [comment]
Let will test a different image and also consider other options.  
Are you using the SAS Viya 4 Infrastructure as Code (IaC) tools to create a cluster?   What is your cloud provider?
Microsoft Azure] (https://github.com/sassoftware/viya4-iac-azure),  
AWS (https://github.com/sassoftware/viya4-iac-aws), 
GCP (https://github.com/sassoftware/viya4-iac-gcp)
Please let us know. 
Thank you!

**Comment by kevinlinglesas** [comment]
@xelat can you share reported vulnerabilities of the associated image?  quick look at CVEs, I wasn't able to find a vulnerability related to this image, so any insight you have would be great.

**Comment by xelat** [comment]
> Let will test a different image and also consider other options. Are you using the SAS Viya 4 Infrastructure as Code (IaC) tools to create a cluster? What is your cloud provider? Microsoft Azure] (https://github.com/sassoftware/viya4-iac-azure), AWS (https://github.com/sassoftware/viya4-iac-aws), GCP (https://github.com/sassoftware/viya4-iac-gcp) Please let us know. Thank you!

Cloud provider is Microsoft Auzre. Customer didn't use the IaC to build the cluster.

**Comment by xelat** [comment]
> @xelat can you share reported vulnerabilities of the associated image? quick look at CVEs, I wasn't able to find a vulnerability related to this image, so any insight you have would be great.

[node-hello-critical-vulnerability-list.xlsx](https://github.com/sassoftware/viya4-ark/files/11828128/node-hello-critical-vulnerability-list.xlsx)

**Comment by xelat** [comment]
The vulnerability report is removed by the bot. Please find the report from [here](https://www.dropbox.com/s/i8pcbtsufxxbaea/node-hello-critical-vulnerability-list.xlsx?dl=0)

**Comment by kevinlinglesas** [comment]
We have created issue #200 for removing the feature that is using the node-hello image, so there will be nothing more specific related to this issue.   Therefore, closing.
