### ISSUE TITLE
Deployment Report is not reporting the first party cloud database info in recent cadences

### ISSUE THREAD

**Issue by lasiva** [sassoftware/viya4-ark#198]
Reported in cadence 2023.06
Refactor for changes in database names/locations that were used in previous cadences to generate the first party cloud postgres database storage information in the deployment report.

**Comment by kevinlinglesas** [comment]
This issue is addressed in [Release 2.0.0](https://github.com/sassoftware/viya4-ark/releases/tag/2.0.0).
