### ISSUE TITLE
Deployment Report: Refactor to use argparse instead of getopts

### ISSUE THREAD

**Issue by sasjowood** [sassoftware/viya4-ark#20]
The Python argparse module provides almost exactly the same feature as getopts but with much less technical overhead and a lot more built in validation and handling of arguments. The download_pod_logs command has been updated to use argparse. The deployment report should also be updated.

**Comment by kevinlinglesas** [comment]
Closing.  Addressed by [v1.0.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.0.0)
