### ISSUE TITLE
Deployment Report: Refactor to use LRPIndicator while task runs

### ISSUE THREAD

**Issue by sasjowood** [sassoftware/viya4-ark#22]
In a recent push, the LRPIndicator class was added to present a visual indicator on the command line while a long-running process is executing. The deployment-report should be refactor to use this class for visual consistency and because execution time may be extended if logs or resource definitions are included.

**Comment by kevinlinglesas** [comment]
Closing.  Addressed by [v1.0.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.0.0)
