### ISSUE TITLE
Indicate Permissions of Insufficient for Azure Persistent Volume Claims if Storage Classes cannot be read

### ISSUE THREAD

**Issue by lasiva** [sassoftware/viya4-ark#29]
If kubeconfig file does not permit listing of storage classes mark the azure storage PVCs Insufficient or  Not Applicable

**Comment by kevinlinglesas** [comment]
Closing.  Addressed by [v1.0.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.0.0)
