### ISSUE TITLE
istio not supported for 2020.0.6 - adjust checker tool

### ISSUE THREAD

**Issue by sasefj** [sassoftware/viya4-ark#34]
As of a decision made on 15Oct, Istio will not be supported for 2020.0.6.  You can see the updated System Requirements:

Kubernetes Cluster Requirements
An Ingress controller,such as NGINX, that is supported by Kubernetes
Istio is not supported.

It would be helpful if the pre-install check report warns folks if it detects istio and not NGINX in the cluster.

**Comment by kevinlinglesas** [comment]
Closing.  Addressed by [v1.0.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.0.0)
Note: This issue not advertised in v1.0.0 description.
