### ISSUE TITLE
Provide guidance to determine Ingress Host and port

### ISSUE THREAD

**Issue by lasiva** [sassoftware/viya4-ark#40]
Currently, there is no guidance on determining the Ingress Host and Port values on Azure with nginx.   Adding some hints and examples to assist the user.

Adding it to README, but may need to be moved to a different section or separate document.

**Comment by kevinlinglesas** [comment]
Closing.  Addressed by [v1.0.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.0.0)
