### ISSUE TITLE
Suggestion: pre-installation check should be designed to be periodically executable

### ISSUE THREAD

**Issue by erwangranger** [sassoftware/viya4-ark#44]
Hello, 

following some discussions with colleagues, I thought it would be good to open an issue on this topic. 

Although we have a tendency to think of pre-reqs as a one-time thing you check before first deployment, I believe that is not the optimal design. 

For various reasons, pre-reqs that were done before a Viya deployment, could be later un-done. For example, someone might mistakenly delete components that are critical to Viya. (Ingress Controller, Cert-Manager), etc.. 
Or, someone might replace 10 very powerful nodes with 3 much less powerful nodes. 

In those situations, the Viya Admin might be un-aware in the changes happening at those levels. All that would be visible would be a suddenly mis-behaving Viya environment. The admin would look to Viya as the culprit when really the fault lies somewhere else. 

Instead, it would be much nicer is some sort of alert was raised as soon as some pre-reqs are suddenly "missing". 

Therefore, I'd propose that the pre-installation report:

1. Have a clear "pass/fail" output, like 0 failures is a pass, and anything greater than 1 is a fail. 
1. Be designed in a way that it can fairly easily be executed over and over, either within kubernetes itself, or from some sort of third-party external tool. (Jenkins, cron, etc...)
1. Take into account that not all the pre-reqs are exactly the same once Viya is actually deployed. If you needed X spare capacity before Viya was running in the cluster, you clearly don't need as much once Viya is deployed. 
1. Allow for the evolution of the software and its pre-reqs. It's likely that as time goes by, those pre-reqs will change. It would be nice to be able to run the same report with different Viya versions, so that I could easily see that although I have all the pre-reqs for Viya LTS-2020.1, I am missing 2 pre-reqs for Viya LTS-2021.1. This is important not just for new deployments, but also for updates from one version to the next. 

I hope this makes sense, and can help with the future design.

**Comment by AlissaSchleich** [comment]
Have entered this as a feature request.  It is under review.
