### ISSUE TITLE
Remove Control Plane Information

### ISSUE THREAD

**Issue by lasiva** [sassoftware/viya4-ark#45]
Status field has extra and/or bad information.  
The following will be removed from the report: 
![image](https://user-images.githubusercontent.com/45047672/98838669-97386980-2412-11eb-9aa3-4dc160349126.png)

**Comment by kevinlinglesas** [comment]
Closing.  Addressed by [v1.0.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.0.0)
