### ISSUE TITLE
Modify Information for Determining Ingress Port

### ISSUE THREAD

**Issue by lasiva** [sassoftware/viya4-ark#49]
The comands for extracting Ingree port need to be changed from "port" to "nodePort'

{{$ export INGRESS_HTTP_PORT=$(kubectl -n <ingress-namespace> get service <nginx-ingress-controller-name> -o jsonpath='
{.spec.ports[?(@.name=="http")].***nodePort**}')*}}

{{$ export INGRESS_HTTPS_PORT=$(kubectl -n <ingress-namespace> get service <nginx-ingress-controller-name> -o sonpath='
{.spec.ports[?(@.name=="https")]*.**nodePort**}')*}}

**Comment by kevinlinglesas** [comment]
Closing.  Addressed by [v1.0.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.0.0)
