### ISSUE TITLE
Deployment Report: request to add cadence version to the report

### ISSUE THREAD

**Issue by cuddlehub** [sassoftware/viya4-ark#60]
Viya 4 introduced the concept of Cadence based releases.
All cadences represent software that has gone through the quality gates and promotion stages prior to being made available to customers.
This is to request adding cadence version to the deployment report.

**Comment by kevinlinglesas** [comment]
Issue addressed in [release 1.1.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.1.0).
