### ISSUE TITLE
CHANGELOG updates

### ISSUE THREAD

**Issue by AddeGroot** [sassoftware/viya4-ark#67]
The Changelog of the most recent version (viya-ark 1.12 does not seem to have the latest updates.
Could they be added?

**Comment by kevinlinglesas** [comment]
@AddeGroot , you are confusing https://github.com/sassoftware/viya-ark (Viya ARK for Viya 3.5) and this repo https://github.com/sassoftware/viya4-ark (Viya 4 ARK for Viya 4).   These are two different projects in github.  The https://github.com/sassoftware/viya-ark/blob/master/CHANGELOG.md is updated with changes for [Viya35-ark-1.12](https://github.com/sassoftware/viya-ark/releases/tag/Viya35-ark-1.12).   There is not CHANGELOG file in viya4-ark (this repo).
