### ISSUE TITLE
Deployment Report: Orphaned pods can cause null dictionary keys in the `sas_components` dictionary yielding sort errors

### ISSUE THREAD

**Issue by sasjowood** [sassoftware/viya4-ark#74]
Currently, if a pod is orphaned (say, a job is deleted without a cascading deletion and its dependent pods are left around), a `null` key is written into the `sas_components` dictionary collected for the deployment report. This `null` key will cause issues when sorting the dictionary as standard sort comparisons (e.g., `<`, `>`) don't support NoneType operands.

The fix is trivial. There is an `if / elif` statement determining when the `component_name` is determined for a SAS component, and that value is ultimately used as the key when it's inserted into the `sas_components` dictionary. The `if / elif` is too restrictive and, in scenarios where the pod owner has been removed, can cause the `component_name` to be `null`. Adjusting the logic to `if / else` fixes this corner case and provides the same functionality as is currently implemented. However, the pod will set a component name and owning objects can update that value if necessary.

**Comment by kevinlinglesas** [comment]
Release [1.2.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.2.0) satisfies this issue.
