### ISSUE TITLE
Download Pod Logs: Error raised when log line is parsed as JSON but is not structured as a dictionary

### ISSUE THREAD

**Issue by sasjowood** [sassoftware/viya4-ark#81]
When pod logs are downloaded and parsed, an error can be raised if the log line contains a value that can be parsed as valid JSON but not returned as a Python-native dictionary (i.e. numbers, raw strings, boolean values, lists). The code expects a dictionary to be returned and checks for the presence of certain required keys. However, unless a JSON object is parsed, the Python-native value may not be a dictionary. To fix this, the parsing class needs to be updated to check if the value returned is a dictionary and, if not, return the line as a string without attempting to parse.

**Comment by kevinlinglesas** [comment]
Release [1.2.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.2.0) satisfies this issue.
