### ISSUE TITLE
deployment report issue

### ISSUE THREAD

**Issue by kurthaemmerle** [sassoftware/viya4-ark#92]
Generating deployment report......................DONE
Traceback (most recent call last):
  File "viya-ark.py", line 139, in <module>
    main(sys.argv[1:])
  File "viya-ark.py", line 77, in main
    command.run(argv[1:])
  File "/sasinstall/viya4-ark-master/deployment_report/deployment_report.py", line 48, in run
    main(argv)
  File "/sasinstall/viya4-ark-master/deployment_report/deployment_report.py", line 149, in main
    include_resource_definitions=args.include_resource_definitions)
  File "/sasinstall/viya4-ark-master/deployment_report/model/viya_deployment_report.py", line 532, in write_report
    data_json = json.dumps(self._report_data, cls=KubernetesObjectJSONEncoder, indent=4, sort_keys=True)
  File "/usr/bin/python3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/bin/python3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/bin/python3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/bin/python3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/bin/python3.7/lib/python3.7/json/encoder.py", line 353, in _iterencode_dict
    items = sorted(dct.items(), key=lambda kv: kv[0])
TypeError: '<' not supported between instances of 'NoneType' and 'str'

**Comment by sasjowood** [comment]
Hi @kurthaemmerle,

This appears to be the same problem reported in Issue #74. The fix will be included in the upcoming 1.2.0 release of this tool. Until then, you can use the "develop" branch of this project, which contains the fix. Please feel free to re-open this issue if you still encounter this problem while using the "develop" branch.

Thanks!

**Comment by kurthaemmerle** [comment]
Hi,

Thanks for the reply.
That helps and did work properly for me now 😊.

Best Regards,

Kurt Hämmerle
Senior Pre-Sales Technical Architect ഄ DACH Customer Advisory Services
Tel: +41 44 805 74 67 ഄ Mobile: +41 79 745 16 53 ഄ ***@***.******@***.***>
SAS Institute AG ഄ Richtistrasse 11 ഄ CH-8304 Wallisellen ഄ www.sas.com/ch<http://www.sas.com/ch>

Von: Josh Woods ***@***.***>
Gesendet: Montag, 26. April 2021 15:22
An: sassoftware/viya4-ark ***@***.***>
Cc: Kurt Hämmerle ***@***.***>; Mention ***@***.***>
Betreff: Re: [sassoftware/viya4-ark] deployment report issue (#92)


EXTERNAL

Hi @kurthaemmerle<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkurthaemmerle&data=04%7C01%7Ckurt.haemmerle%40sas.com%7Cf2d95872a7ce4ab1e51508d908b64c45%7Cb1c14d5c362545b3a4309552373a0c2f%7C0%7C0%7C637550401326463061%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2Bzbvv6MeYvKid%2FhfBOW8Y1K2l8vl%2Fwpf1DJ0VvTeu3M%3D&reserved=0>,

This appears to be the same problem reported in Issue #74<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsassoftware%2Fviya4-ark%2Fissues%2F74&data=04%7C01%7Ckurt.haemmerle%40sas.com%7Cf2d95872a7ce4ab1e51508d908b64c45%7Cb1c14d5c362545b3a4309552373a0c2f%7C0%7C0%7C637550401326473059%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oNRmaR4gHzn1p3AePYbJs8JRixvLS4DMSpvrlIO%2Fsdc%3D&reserved=0>. The fix will be included in the upcoming 1.2.0 release of this tool. Until then, you can use the "develop" branch of this project, which contains the fix. Please feel free to re-open this issue if you still encounter this problem while using the "develop" branch.

Thanks!
