### ISSUE TITLE
LDAP Validator

### ISSUE THREAD

**Issue by lasiva** [sassoftware/viya4-ark#98]
The tool does not allow/perform an anonymous bind.  It uses bind User DN and password to authenticate.  If  **anonymousBind** is included in the yaml file, the value must be set to false.  If the the user's sitedefault yaml file includes 'anonymousBind: true' then display error message and exit.  Modify and also update README

**Comment by kevinlinglesas** [comment]
Release [1.2.1](https://github.com/sassoftware/viya4-ark/releases/tag/1.2.1) satisfies this issue.
